name: Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Validate content metadata
        run: uv run scripts/validate.py
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.10.18
      - name: Render site
        run: quarto render
